version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./user-service
    ports:
      - "5001:80"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27017
    env_file:
      - ./user-service/.env

  product-service:
    build: ./product-service
    ports:
      - "5002:80"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27017
    env_file:
      - ./product-service/.env

  order-service:
    build: ./order-service
    ports:
      - "5003:80"
    depends_on:
      - user-service
      - product-service
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27017
    # env_file:
      # - ./order-service/.env

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:80"
    depends_on:
      - user-service
      - product-service
      - order-service
    # env_file:
      # - ./api-gateway/.env

volumes:
  mongo_data:
